# Generated by Django 4.2.7 on 2023-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadmin', models.AutoField(db_column='idAdmin', primary_key=True, serialize=False)),
                ('nombreadmin', models.CharField(db_column='nombreAdmin', max_length=30)),
                ('appatadmin', models.CharField(db_column='apPatAdmin', max_length=30)),
                ('apmatadmin', models.CharField(db_column='apMatAdmin', max_length=30)),
                ('contraadmin', models.CharField(db_column='contraAdmin', max_length=126)),
                ('correoadmin', models.CharField(db_column='correoAdmin', max_length=35)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogozonas',
            fields=[
                ('idzona', models.AutoField(db_column='idZona', primary_key=True, serialize=False)),
                ('colonia', models.CharField(max_length=50)),
                ('codigopostal', models.IntegerField(db_column='codigoPostal')),
            ],
            options={
                'db_table': 'catalogozonas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombrecliente', models.CharField(db_column='nombreCliente', max_length=30)),
                ('appatcliente', models.CharField(db_column='apPatCliente', max_length=30)),
                ('apmatcliente', models.CharField(db_column='apMatCliente', max_length=30)),
                ('contracliente', models.CharField(db_column='contraCliente', max_length=126)),
                ('correocliente', models.CharField(db_column='correoCliente', max_length=35)),
                ('callecliente', models.CharField(db_column='calleCliente', max_length=15)),
                ('colcliente', models.CharField(db_column='colCliente', max_length=20)),
                ('numextcliente', models.CharField(db_column='numExtCliente', max_length=5)),
                ('cpcliente', models.IntegerField(db_column='cpCliente')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportefallas',
            fields=[
                ('idfalla', models.AutoField(db_column='idFalla', primary_key=True, serialize=False)),
                ('motivorep', models.CharField(db_column='motivoRep', max_length=50)),
                ('fecharep', models.DateField(db_column='fechaRep')),
                ('estatusrep', models.CharField(db_column='estatusRep', max_length=20)),
            ],
            options={
                'db_table': 'reportefallas',
                'managed': False,
            },
        ),
    ]
